import { Nunito_Sans, Roboto } from "next/font/google";
import "./globals.css";

const nunito = Nunito_Sans({ subsets: ["latin"], variable: "--primary-font", weight: "variable" });
const roboto = Roboto({ subsets: ["latin"], variable: "--secondary-font", weight: ["300", "400", "500", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>{children}</body>
    </html>
  );
}
